git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/deadbeef
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/devtools
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/gpicview
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/ldm-gtk-builder-greeter
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxadmin
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxappearance
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxappearance-obconf
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxde
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxde-common
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxde-common-qt
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxde-icon-theme
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxdm
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lximage-qt
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxinput
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxinput-qt
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxkb_config
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxlauncher
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxmenu-data
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxmusic
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpanel
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpanel-plugins
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpanel-qt
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpanel-xmms2
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpanel2
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxpolkit
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxrandr
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxrandr-qt
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxscreenshot
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxsession
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxsession-edit
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxshortcut
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxsysmon
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxtask
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/lxterminal
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/menu-cache
git submodule add git://lxde.git.sourceforge.net/gitroot/lxde/obconf-qt
